name: linter
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Gradle Build
      uses: joschi/setup-jdk@v2
      with:
        java-version: 15
        architecture: x64
    - run: gradle build


